unit TefTipos;

interface

type

  FORMA_PAGAMENTO_TYPE = (CREDITO,DEBITO,TODOS);
  PARCELAMENTO_TYPE = (LOJA,ADM,NENHUM);
  TRANSACAO_TYPE =(VENDA,CANCELAMENTO,CONFIGURACAO,NONE);

implementation

end.
